### ISSUE TITLE
Çalışmadı

### ISSUE THREAD

**Issue by burhanaksendir** [berkturk/parse.com#1]
Merhaba,
kodları denedim ama çalışmıyor. Güncelleme mevcut mu ?

**Comment by berkturk** [comment]
ApplicationID
Rest Api Key

alanlarını kendi bilgilerinize göre güncellediniz mi?

**Comment by burhanaksendir** [comment]
Sağolun. Localhost'ta denediğim için olmamış :) Sunucuya yükleyince çalıştı.
